### ISSUE TITLE
10.2.7 Anchor errors

### ISSUE THREAD

**Issue by TheZade** [Xuerian/XLoot#31] opened 2024-05-11 21:02 UTC
174790x XLoot_Group/Group.lua:988: attempt to index upvalue 'anchor' (a nil value)
[string "@XLoot_Group/Group.lua"]:988: in function `ApplyOptions'
[string "@XLoot/XLoot.lua"]:74: in function `ApplyOptions'
[string "@XLoot_Options/Options.lua"]:87: in function <XLoot_Options/Options.lua:85>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 OnInitialize = <function> defined @XLoot_Group/Group.lua:91
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 ToggleAnchors = <function> defined @XLoot_Group/Group.lua:536
 defaultModuleLibraries = <table> {
 }
 LOOT_HISTORY_ROLL_COMPLETE = <function> defined @XLoot_Group/Group.lua:297
 MODIFIER_STATE_CHANGED = <function> defined @XLoot_Group/Group.lua:435
 UpdateAnchors = <function> defined @XLoot_Group/Group.lua:531
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 name = "XLoot_Group"
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 TestSettings = <function> defined @XLoot_Group/Group.lua:1023
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 START_LOOT_ROLL = <function> defined @XLoot_Group/Group.lua:206
 LOOT_HISTORY_ROLL_CHANGED = <function> defined @XLoot_Group/Group.lua:360
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 AlertFrameHook = <function> defined @XLoot_Group/Group.lua:442
 ShowOptions = <function> defined @XLoot/XLoot.lua:89
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 opt = <table> {
 }
 enabledState = true
 baseName = "XLoot_Group"
 LOOT_ROLLS_COMPLETE = <function> defined @XLoot_Group/Group.lua:297
 ApplyOptions = <function> defined @XLoot_Group/Group.lua:985
 SlashHandler = <function> defined @XLoot_Group/Group.lua:520
 SkinUpdate = <function> defined @XLoot_Group/Group.lua:964
 bars = <table> {
 }
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 OnEnable = <function> defined @XLoot_Group/Group.lua:99
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 moduleName = "Group"
 defaultModuleState = true
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'anchor' (a nil value)"
opt = <table> {
 track_player_roll = false
 prefix_upgrade = "+"
 expire_won = 20
 role_icon = true
 hook_alert = false
 show_time_remaining = false
 shown_hook_warning = false
 alert_scale = 1
 bonus_skin = true
 track_threshold = 3
 text_ilvl = false
 alert_icon_frame = false
 roll_width = 325
 hook_bonus = false
 show_decided = true
 track_by_threshold = true
 font = "Fonts\FRIZQT__.TTF"
 alert_skin = true
 roll_button_size = 28
 alert_alpha = 1
 alert_background = false
 prefix_equippable = "*"
 alert_anchor = <table> {
 }
 equip_prefix = true
 win_icon = true
 expire_lost = 10
 font_flag = "OUTLINE"
 roll_anchor = <table> {
 }
 track_all = false
 alert_offset = 4
 show_undecided = true
}
anchor = nil
alert_anchor = nil

**Comment by Xuerian** [comment] 2024-05-17 02:25
XLoot Group has been broken ever since the API changes to group loot.

Is 10.2.7 modern or classic? I have not kept up with anything.

**Comment by Xuerian** [comment] 2024-07-09 17:29
Closing as duplicate of #23

**Closed by Xuerian** 2024-07-09 17:29 UTC
