### ISSUE TITLE
Error bossloot

### ISSUE THREAD

**Issue by skorpantre** [Xuerian/XLoot#26] opened 2024-02-24 23:29 UTC
im getting "error" text  ( you know the bog black box with code) every time im looting a boss in raids its not every time it hapens in legacy raids but in all the dragonflight raid bosses im getting the error

**Comment by Xuerian** [comment] 2024-03-05 01:01
I'll need the actual text of the error to have any hope of fixing it.

**Comment by Nulgar** [comment] 2024-07-04 19:53
```
[21:45:19] Interface/AddOns/XLoot_Group/Group.lua:226: attempt to index upvalue 'anchor' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/XLoot_Group/Group.lua"]:226: in function `?'
[string "@Interface/AddOns/XLoot/XLoot.lua"]:41: in function <Interface/AddOns/XLoot/XLoot.lua:39>

```

**Comment by Xuerian** [comment] 2024-07-08 21:50
Aha, yes, Group is not yet updated for the recent API changes, see #23

**Comment by Xuerian** [comment] 2024-07-09 17:30
Closing as duplicate of #23

**Closed by Xuerian** 2024-07-09 17:30 UTC
