### ISSUE TITLE
Classic Era Update 1.15.1

### ISSUE THREAD

**Issue by maximus210793** [Xuerian/XLoot#27] opened 2024-03-10 16:31 UTC
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.1?
Would be awesome, thanks a lot in advance!

**Comment by Xuerian** [comment] 2024-05-17 02:26
Thanks for your appreciation, glad you've liked the addon!

What about it isn't working in 1.15.1?

**Comment by Xuerian** [comment] 2024-07-09 17:29
Closing as duplicate of #23

**Closed by Xuerian** 2024-07-09 17:29 UTC
